### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by craigs78** [stuartpittaway/emoncmsOctopusSmartMeter#1]
Hi trying to run this on a mac, with Pyhon 3.8
But getting this error. 
  
File "./import_octopus.py", line 38, in <module>
    from emoncmsapi import emoncmsapi
  File "/Users/craig/Downloads/emoncmsOctopusSmartMeter-master/emoncmsapi.py", line 10, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Thanks

**Comment by stuartpittaway** [comment]
You need to install the dependant modules.

Take a look at PIP

https://en.m.wikipedia.org/wiki/Pip_(package_manager)

**Comment by craigs78** [comment]
Great thanks a Lot for your help, first time in doing this..
All done now :)
